export const battlers = [
    {
        id: 1,
        name: "Loaded Lux",
        location: "Harlem, NY",
        image: "/placeholder.svg?height=300&width=300",
        tags: ["URL", "Veteran"],
    },
    {
        id: 2,
        name: "Tsu Surf",
        location: "Newark, NJ",
        image: "/placeholder.svg?height=300&width=300",
        tags: ["URL", "Puncher"],
    },
    {
        id: 3,
        name: "Geechi Gotti",
        location: "Compton, CA",
        image: "/placeholder.svg?height=300&width=300",
        tags: ["URL", "Performance"],
    },
    {
        id: 4,
        name: "Rum Nitty",
        location: "Phoenix, AZ",
        image: "/placeholder.svg?height=300&width=300",
        tags: ["URL", "Puncher"],
    },
    {
        id: 5,
        name: "JC",
        location: "Pontiac, MI",
        image: "/placeholder.svg?height=300&width=300",
        tags: ["URL", "Lyricist"],
    },
    {
        id: 6,
        name: "K-Shine",
        location: "Harlem, NY",
        image: "/placeholder.svg?height=300&width=300",
        tags: ["URL", "Performance"],
    },
    {
        id: 7,
        name: "Hitman Holla",
        location: "St. Louis, MO",
        image: "/placeholder.svg?height=300&width=300",
        tags: ["URL", "Performance"],
    },
    {
        id: 8,
        name: "Charlie Clips",
        location: "Harlem, NY",
        image: "/placeholder.svg?height=300&width=300",
        tags: ["URL", "Freestyle"],
    },
    {
        id: 9,
        name: "Daylyt",
        location: "Watts, CA",
        image: "/placeholder.svg?height=300&width=300",
        tags: ["URL", "Lyricist"],
    },
    {
        id: 10,
        name: "T-Rex",
        location: "Harlem, NY",
        image: "/placeholder.svg?height=300&width=300",
        tags: ["URL", "Veteran"],
    },
    {
        id: 11,
        name: "Aye Verb",
        location: "St. Louis, MO",
        image: "/placeholder.svg?height=300&width=300",
        tags: ["URL", "Veteran"],
    },
    {
        id: 12,
        name: "Murda Mook",
        location: "Harlem, NY",
        image: "/placeholder.svg?height=300&width=300",
        tags: ["URL", "Veteran"],
    },
]

export const battlerDetails = {
    id: 1,
    name: "Loaded Lux",
    location: "Harlem, NY",
    image: "/placeholder.svg?height=400&width=400",
    banner: "/placeholder.svg?height=200&width=1200",
    tags: ["URL", "Veteran", "Lyricist"],
    totalPoints: 8.7,
}


export const popularTags = [
    "URL",
    "RBE",
    "KOTD",
    "East Coast",
    "West Coast",
    "Midwest",
    "Puncher",
    "Lyricist",
    "Performance",
    "Veteran",
    "New School",
]