export const recentBattlers = [
  {
    id: 1,
    name: "Loaded Lux",
    location: "Harlem, NY",
    image: "/placeholder.svg?height=300&width=300",
  },
  {
    id: 2,
    name: "Tsu Surf",
    location: "Newark, NJ",
    image: "/placeholder.svg?height=300&width=300",
  },
  {
    id: 3,
    name: "Geechi Gotti",
    location: "Compton, CA",
    image: "/placeholder.svg?height=300&width=300",
  },
  {
    id: 4,
    name: "Rum Nitty",
    location: "Phoenix, AZ",
    image: "/placeholder.svg?height=300&width=300",
  },
  {
    id: 5,
    name: "JC",
    location: "Pontiac, MI",
    image: "/placeholder.svg?height=300&width=300",
  },
  {
    id: 6,
    name: "K-Shine",
    location: "Harlem, NY",
    image: "/placeholder.svg?height=300&width=300",
  },
];

export const trendingBattlers = [
  {
    id: 1,
    name: "Loaded Lux",
    image: "/placeholder.svg?height=300&width=300",
    location: "Harlem, NY",
    rating: 9.2,
    change: 0.3,
    spotlightBadges: ["Wordsmith", "Scheme King", "Crowd Control"],
  },
  {
    id: 2,
    name: "Geechi Gotti",
    image: "/placeholder.svg?height=300&width=300",
    location: "Compton, CA",
    rating: 9.0,
    change: 0.5,
    spotlightBadges: ["Authentic", "Consistent", "Performance"],
  },
  {
    id: 3,
    name: "Rum Nitty",
    image: "/placeholder.svg?height=300&width=300",
    location: "Phoenix, AZ",
    rating: 8.9,
    change: 0.2,
    spotlightBadges: ["Puncher", "Wordplay", "Technical"],
  },
  {
    id: 4,
    name: "Tsu Surf",
    image: "/placeholder.svg?height=300&width=300",
    location: "Newark, NJ",
    rating: 8.7,
    change: -0.1,
    spotlightBadges: ["Performance", "Crowd Control", "Freestyle"],
  },
];

export const communityStats = {
  totalRatings: 12458,
  activeUsers: 843,
  recentBattles: 24,
  topBadges: [
    { badge: "Wordsmith", count: 342 },
    { badge: "Puncher", count: 287 },
    { badge: "Performance", count: 256 },
    { badge: "Consistent", count: 198 },
    { badge: "Crowd Control", count: 176 },
  ],
  activityData: [
    { date: "Jan", ratings: 720 },
    { date: "Feb", ratings: 832 },
    { date: "Mar", ratings: 901 },
    { date: "Apr", ratings: 934 },
    { date: "May", ratings: 1290 },
    { date: "Jun", ratings: 1330 },
    { date: "Jul", ratings: 1450 },
  ],
};

export const spotlightAnalytics = [
  {
    title: "Top Performing Attributes",
    description: "Highest rated attributes across all battlers",
    chartData: [
      { name: "Wordplay", value: 8.7 },
      { name: "Delivery", value: 8.5 },
      { name: "Authenticity", value: 8.9 },
      { name: "Battle IQ", value: 9.1 },
      { name: "Crowd Control", value: 8.3 },
    ],
    dataKey: "value",
    color: "#8B5CF6",
  },
  {
    title: "Most Improved Battlers",
    description: "Battlers with the biggest rating increases",
    chartData: [
      { name: "Geechi Gotti", value: 0.8 },
      { name: "Tay Roc", value: 0.6 },
      { name: "Chess", value: 0.5 },
      { name: "Rum Nitty", value: 0.4 },
      { name: "JC", value: 0.3 },
    ],
    dataKey: "value",
    color: "#10B981",
  },
  {
    title: "Most Assigned Badges",
    description: "Most frequently assigned badges by the community",
    chartData: [
      { name: "Wordsmith", value: 342 },
      { name: "Puncher", value: 287 },
      { name: "Performance", value: 256 },
      { name: "Consistent", value: 198 },
      { name: "Crowd Control", value: 176 },
    ],
    dataKey: "value",
    color: "#F59E0B",
  },
];

export const highlightedBattlers = [
  {
    id: 1,
    name: "Loaded Lux",
    image: "/placeholder.svg?height=400&width=400",
    location: "Harlem, NY",
    rating: 9.2,
    bio: "Loaded Lux is known for his intricate wordplay, complex schemes, and philosophical approach to battle rap. His performances are often characterized by deeply researched angles and memorable catchphrases.",
    accolades: ["3x Champion of the Year", "Most Quoted Battler", "Highest Rated Performance"],
    badges: ["Wordsmith", "Scheme King", "Crowd Control", "Battle IQ", "Preparation"],
    tags: ["Veteran", "East Coast", "URL", "Lyricist"],
  },
  {
    id: 2,
    name: "Geechi Gotti",
    image: "/placeholder.svg?height=400&width=400",
    location: "Compton, CA",
    rating: 9.0,
    bio: "Geechi Gotti is known for his authentic street content and consistent performances. He's a multiple Champion of the Year winner who brings credibility and relatability to every battle.",
    accolades: ["3x Champion of the Year", "Most Consistent", "Fan Favorite"],
    badges: ["Authentic", "Consistent", "Performance", "Crowd Control"],
    tags: ["West Coast", "URL", "Street"],
  },
  {
    id: 3,
    name: "Rum Nitty",
    image: "/placeholder.svg?height=400&width=400",
    location: "Phoenix, AZ",
    rating: 8.9,
    bio: "Rum Nitty is regarded as one of the best punchers in battle rap history. His ability to craft complex punchlines and deliver them effectively has made him a fan favorite.",
    accolades: ["Puncher of the Year", "Most Quotable", "Performance of the Year"],
    badges: ["Puncher", "Wordplay", "Creativity", "Quotable"],
    tags: ["West Coast", "URL", "Puncher"],
  },
  {
    id: 4,
    name: "40 B.A.R.S.",
    image: "/placeholder.svg?height=400&width=400",
    location: "Philadelphia, PA",
    rating: 8.7,
    bio: "40 B.A.R.S. is known for her technical ability and precise delivery. She combines wordplay with aggressive performance to create memorable moments.",
    accolades: ["Queen of the Ring Champion", "Best Female Performance", "Most Technical"],
    badges: ["Technical", "Wordplay", "Performance", "Preparation"],
    tags: ["East Coast", "QOTR", "lady", "Technical"],
  },
  {
    id: 5,
    name: "Shotgun Suge",
    image: "/placeholder.svg?height=400&width=400",
    location: "Newark, NJ",
    rating: 8.5,
    bio: "Shotgun Suge is known for his aggressive style and commanding stage presence. His physical performance and crowd control make him a formidable opponent.",
    accolades: ["Most Aggressive", "Best Stage Presence", "Fan Favorite"],
    badges: ["Performance", "Aggression", "Stage Presence", "Crowd Control"],
    tags: ["East Coast", "URL", "Performance"],
  },
  {
    id: 6,
    name: "Shox The Rebel",
    image: "/placeholder.svg?height=400&width=400",
    location: "London, UK",
    rating: 8.6,
    bio: "Shox The Rebel is one of the UK's premier battle rappers, known for his precise delivery and punching ability. He combines technical skill with performance to create impactful moments.",
    accolades: [
      "UK Battle Rapper of the Year",
      "International Breakthrough",
      "Technical Excellence",
    ],
    badges: ["Technical", "Puncher", "International", "Precise"],
    tags: ["UK", "Don't Flop", "international", "Technical"],
  },
];

export const rankingSystemBattlers = [
  {
    id: "1",
    name: "Loaded Lux",
    image: "/placeholder.svg?height=300&width=300",
    location: "Harlem, NY",
    weightedRating: 9.2,
    unweightedRating: 8.9,
    change: 0.3,
    lastUpdated: "2 days ago",
    badges: ["Wordsmith", "Scheme King"],
    tags: ["URL", "Veteran", "East Coast"],
    userType: "battler",
  },
  {
    id: "2",
    name: "Geechi Gotti",
    image: "/placeholder.svg?height=300&width=300",
    location: "Compton, CA",
    weightedRating: 9.0,
    unweightedRating: 9.1,
    change: 0.5,
    lastUpdated: "1 day ago",
    badges: ["Authentic", "Consistent"],
    tags: ["URL", "West Coast", "COTY"],
  },
  {
    id: "3",
    name: "Rum Nitty",
    image: "/placeholder.svg?height=300&width=300",
    location: "Phoenix, AZ",
    weightedRating: 8.9,
    unweightedRating: 8.7,
    change: 0.2,
    lastUpdated: "3 days ago",
    badges: ["Puncher", "Wordplay"],
    tags: ["URL", "West Coast", "Puncher"],
  },
  {
    id: "4",
    name: "Tsu Surf",
    image: "/placeholder.svg?height=300&width=300",
    location: "Newark, NJ",
    weightedRating: 8.7,
    unweightedRating: 8.8,
    change: -0.1,
    lastUpdated: "5 days ago",
    badges: ["Performance", "Crowd Control"],
    tags: ["URL", "East Coast", "Veteran"],
    userType: "media",
  },
  {
    id: "5",
    name: "JC",
    image: "/placeholder.svg?height=300&width=300",
    location: "Pontiac, MI",
    weightedRating: 8.5,
    unweightedRating: 8.3,
    change: 0.1,
    lastUpdated: "4 days ago",
    badges: ["Lyricist", "Technical"],
    tags: ["URL", "Midwest", "Lyricist"],
  },
  {
    id: "6",
    name: "K-Shine",
    image: "/placeholder.svg?height=300&width=300",
    location: "Harlem, NY",
    weightedRating: 8.3,
    unweightedRating: 8.4,
    change: -0.2,
    lastUpdated: "1 week ago",
    badges: ["Performance", "Energy"],
    tags: ["URL", "East Coast", "Performance"],
    userType: "league_owner",
  },
  {
    id: "7",
    name: "Hitman Holla",
    image: "/placeholder.svg?height=300&width=300",
    location: "St. Louis, MO",
    weightedRating: 8.2,
    unweightedRating: 8.5,
    change: -0.3,
    lastUpdated: "2 weeks ago",
    badges: ["Performance", "Remixes"],
    tags: ["URL", "Midwest", "Performance", "Mainstream"],
  },
  {
    id: "8",
    name: "Charlie Clips",
    image: "/placeholder.svg?height=300&width=300",
    location: "Harlem, NY",
    weightedRating: 8.1,
    unweightedRating: 8.0,
    change: 0.2,
    lastUpdated: "3 days ago",
    badges: ["Freestyle", "Humor"],
    tags: ["URL", "East Coast", "Freestyle", "Veteran"],
  },
];

export const MediaUsers = [
  {
    id: "1",
    name: "Jay Blac",
    image: "/placeholder.svg?height=300&width=300",
    outlet: "Champion",
    bio: "Battle rap analyst and host of Champion",
    socialLinks: {
      youtube: "https://youtube.com",
      twitter: "https://twitter.com",
      instagram: "https://instagram.com",
      website: "https://example.com",
    },
    recentContent: [
      {
        title: "Loaded Lux vs Geechi Gotti - Who Really Won?",
        url: "https://youtube.com",
        type: "video",
        thumbnail: "/placeholder.svg?height=180&width=320",
        likes: 1245,
        date: "2 days ago",
      },
      {
        title: "Top 5 Performances of the Month",
        url: "https://youtube.com",
        type: "video",
        thumbnail: "/placeholder.svg?height=180&width=320",
        likes: 987,
        date: "1 week ago",
      },
    ],
  },
  {
    id: "2",
    name: "15 Minutes of Fame",
    image: "/placeholder.svg?height=300&width=300",
    outlet: "15MOF",
    bio: "Battle rap news and interviews",
    socialLinks: {
      youtube: "https://youtube.com",
      twitter: "https://twitter.com",
    },
    recentContent: [
      {
        title: "Exclusive Interview with Tsu Surf",
        url: "https://youtube.com",
        type: "video",
        thumbnail: "/placeholder.svg?height=180&width=320",
        likes: 876,
        date: "3 days ago",
      },
    ],
  },
  {
    id: "3",
    name: "Battle Rap Trap",
    image: "/placeholder.svg?height=300&width=300",
    outlet: "BRT",
    bio: "Battle rap news, reviews, and predictions",
    socialLinks: {
      youtube: "https://youtube.com",
      website: "https://example.com",
    },
    recentContent: [
      {
        title: "Weekly Battle Rap Roundup",
        url: "https://example.com",
        type: "article",
        likes: 543,
        date: "1 day ago",
      },
      {
        title: "Upcoming Battles You Can't Miss",
        url: "https://example.com",
        type: "article",
        likes: 321,
        date: "4 days ago",
      },
    ],
  },
];
