export const highlightedBattlers = [
  {
    id: 1,
    name: "Loaded Lux",
    image: "/placeholder.svg?height=400&width=400",
    location: "Harlem, NY",
    rating: 9.2,
    bio: "Loaded Lux is known for his intricate wordplay, complex schemes, and philosophical approach to battle rap. His performances are often characterized by deeply researched angles and memorable catchphrases.",
    accolades: ["3x Champion of the Year", "Most Quoted Battler", "Highest Rated Performance"],
    badges: ["Wordsmith", "Scheme King", "Crowd Control", "Battle IQ", "Preparation"],
    tags: ["Veteran", "East Coast", "URL", "Lyricist"],
  },
  {
    id: 2,
    name: "Geechi Gotti",
    image: "/placeholder.svg?height=400&width=400",
    location: "Compton, CA",
    rating: 9.0,
    bio: "Geechi Gotti is known for his authentic street content and consistent performances. He's a multiple Champion of the Year winner who brings credibility and relatability to every battle.",
    accolades: ["3x Champion of the Year", "Most Consistent", "Fan Favorite"],
    badges: ["Authentic", "Consistent", "Performance", "Crowd Control"],
    tags: ["West Coast", "URL", "Street"],
  },
  {
    id: 3,
    name: "Rum Nitty",
    image: "/placeholder.svg?height=400&width=400",
    location: "Phoenix, AZ",
    rating: 8.9,
    bio: "Rum Nitty is regarded as one of the best punchers in battle rap history. His ability to craft complex punchlines and deliver them effectively has made him a fan favorite.",
    accolades: ["Puncher of the Year", "Most Quotable", "Performance of the Year"],
    badges: ["Puncher", "Wordplay", "Creativity", "Quotable"],
    tags: ["West Coast", "URL", "Puncher"],
  },
  {
    id: 4,
    name: "40 B.A.R.S.",
    image: "/placeholder.svg?height=400&width=400",
    location: "Philadelphia, PA",
    rating: 8.7,
    bio: "40 B.A.R.S. is known for her technical ability and precise delivery. She combines wordplay with aggressive performance to create memorable moments.",
    accolades: ["Queen of the Ring Champion", "Best Female Performance", "Most Technical"],
    badges: ["Technical", "Wordplay", "Performance", "Preparation"],
    tags: ["East Coast", "QOTR", "lady", "Technical"],
  },
  {
    id: 5,
    name: "Shotgun Suge",
    image: "/placeholder.svg?height=400&width=400",
    location: "Newark, NJ",
    rating: 8.5,
    bio: "Shotgun Suge is known for his aggressive style and commanding stage presence. His physical performance and crowd control make him a formidable opponent.",
    accolades: ["Most Aggressive", "Best Stage Presence", "Fan Favorite"],
    badges: ["Performance", "Aggression", "Stage Presence", "Crowd Control"],
    tags: ["East Coast", "URL", "Performance"],
  },
  {
    id: 6,
    name: "Shox The Rebel",
    image: "/placeholder.svg?height=400&width=400",
    location: "London, UK",
    rating: 8.6,
    bio: "Shox The Rebel is one of the UK's premier battle rappers, known for his precise delivery and punching ability. He combines technical skill with performance to create impactful moments.",
    accolades: [
      "UK Battle Rapper of the Year",
      "International Breakthrough",
      "Technical Excellence",
    ],
    badges: ["Technical", "Puncher", "International", "Precise"],
    tags: ["UK", "Don't Flop", "international", "Technical"],
  },
];

export const MediaUsers = [
  {
    id: "1",
    name: "Jay Blac",
    image: "/placeholder.svg?height=300&width=300",
    outlet: "Champion",
    bio: "Battle rap analyst and host of Champion",
    socialLinks: {
      youtube: "https://youtube.com",
      twitter: "https://twitter.com",
      instagram: "https://instagram.com",
      website: "https://example.com",
    },
    recentContent: [
      {
        title: "Loaded Lux vs Geechi Gotti - Who Really Won?",
        url: "https://youtube.com",
        type: "video",
        thumbnail: "/placeholder.svg?height=180&width=320",
        likes: 1245,
        date: "2 days ago",
      },
      {
        title: "Top 5 Performances of the Month",
        url: "https://youtube.com",
        type: "video",
        thumbnail: "/placeholder.svg?height=180&width=320",
        likes: 987,
        date: "1 week ago",
      },
    ],
  },
  {
    id: "2",
    name: "15 Minutes of Fame",
    image: "/placeholder.svg?height=300&width=300",
    outlet: "15MOF",
    bio: "Battle rap news and interviews",
    socialLinks: {
      youtube: "https://youtube.com",
      twitter: "https://twitter.com",
    },
    recentContent: [
      {
        title: "Exclusive Interview with Tsu Surf",
        url: "https://youtube.com",
        type: "video",
        thumbnail: "/placeholder.svg?height=180&width=320",
        likes: 876,
        date: "3 days ago",
      },
    ],
  },
  {
    id: "3",
    name: "Battle Rap Trap",
    image: "/placeholder.svg?height=300&width=300",
    outlet: "BRT",
    bio: "Battle rap news, reviews, and predictions",
    socialLinks: {
      youtube: "https://youtube.com",
      website: "https://example.com",
    },
    recentContent: [
      {
        title: "Weekly Battle Rap Roundup",
        url: "https://example.com",
        type: "article",
        likes: 543,
        date: "1 day ago",
      },
      {
        title: "Upcoming Battles You Can't Miss",
        url: "https://example.com",
        type: "article",
        likes: 321,
        date: "4 days ago",
      },
    ],
  },
];
